# Generated by Django 5.0.6 on 2024-05-26 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidade', models.CharField(max_length=255)),
                ('crm', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_exame', models.CharField(max_length=255)),
                ('data_exame', models.DateField()),
                ('resultado', models.TextField(blank=True, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='exames/')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('is_medico', models.BooleanField(default=False)),
                ('is_secretario', models.BooleanField(default=False)),
                ('is_paciente', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pessoa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='pessoa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='core.pessoa'),
        ),
        migrations.AddField(
            model_name='medico',
            name='pessoa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medico', to='core.pessoa'),
        ),
        migrations.CreateModel(
            name='Secretario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medico')),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='secretario', to='core.pessoa')),
            ],
        ),
    ]
